# CMake generated Testfile for 
# Source directory: /home/krish/MTP/ns3/ns-allinone-3.36.1/ns-3.36.1/src/sixlowpan/examples
# Build directory: /home/krish/MTP/ns3/ns-allinone-3.36.1/ns-3.36.1/cmake-cache/src/sixlowpan/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-example-sixlowpan "ns3.36.1-example-sixlowpan-debug")
set_tests_properties(ctest-example-sixlowpan PROPERTIES  WORKING_DIRECTORY "/home/krish/MTP/ns3/ns-allinone-3.36.1/ns-3.36.1/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/home/krish/MTP/ns3/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/krish/MTP/ns3/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/krish/MTP/ns3/ns-allinone-3.36.1/ns-3.36.1/src/sixlowpan/examples/CMakeLists.txt;1;build_lib_example;/home/krish/MTP/ns3/ns-allinone-3.36.1/ns-3.36.1/src/sixlowpan/examples/CMakeLists.txt;0;")
add_test(ctest-example-ping-lr-wpan "ns3.36.1-example-ping-lr-wpan-debug")
set_tests_properties(ctest-example-ping-lr-wpan PROPERTIES  WORKING_DIRECTORY "/home/krish/MTP/ns3/ns-allinone-3.36.1/ns-3.36.1/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/home/krish/MTP/ns3/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/krish/MTP/ns3/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/krish/MTP/ns3/ns-allinone-3.36.1/ns-3.36.1/src/sixlowpan/examples/CMakeLists.txt;12;build_lib_example;/home/krish/MTP/ns3/ns-allinone-3.36.1/ns-3.36.1/src/sixlowpan/examples/CMakeLists.txt;0;")
add_test(ctest-example-ping-lr-wpan-beacon "ns3.36.1-example-ping-lr-wpan-beacon-debug")
set_tests_properties(ctest-example-ping-lr-wpan-beacon PROPERTIES  WORKING_DIRECTORY "/home/krish/MTP/ns3/ns-allinone-3.36.1/ns-3.36.1/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/home/krish/MTP/ns3/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/krish/MTP/ns3/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/krish/MTP/ns3/ns-allinone-3.36.1/ns-3.36.1/src/sixlowpan/examples/CMakeLists.txt;23;build_lib_example;/home/krish/MTP/ns3/ns-allinone-3.36.1/ns-3.36.1/src/sixlowpan/examples/CMakeLists.txt;0;")
add_test(ctest-example-ping-lr-wpan-mesh-under "ns3.36.1-example-ping-lr-wpan-mesh-under-debug")
set_tests_properties(ctest-example-ping-lr-wpan-mesh-under PROPERTIES  WORKING_DIRECTORY "/home/krish/MTP/ns3/ns-allinone-3.36.1/ns-3.36.1/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/home/krish/MTP/ns3/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/krish/MTP/ns3/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/krish/MTP/ns3/ns-allinone-3.36.1/ns-3.36.1/src/sixlowpan/examples/CMakeLists.txt;34;build_lib_example;/home/krish/MTP/ns3/ns-allinone-3.36.1/ns-3.36.1/src/sixlowpan/examples/CMakeLists.txt;0;")
